export function createDefaultCompanyCanvasConfig(): FormCanvasConfig {
  return {
    enabled: true,
    width: 1080,
    height: 1920,
    backgroundColor: "#ffffff",
    elements: [
      {
        id: "required-title",
        type: "text",
        x: 90,
        y: 110,
        width: 900,
        height: 90,
        text: "학점은행제 맞춤 상담 신청",
        fontSize: 54,
        fontWeight: 900,
        fontFamily: "Pretendard, sans-serif",
        color: "#111827",
        textAlign: "center",
        zIndex: 1,
      },
      {
        id: "required-subtitle",
        type: "text",
        x: 120,
        y: 210,
        width: 840,
        height: 70,
        text: "전문 담당자가 학습 상황에 맞춰 무료로 안내드립니다.",
        fontSize: 30,
        fontWeight: 700,
        fontFamily: "Pretendard, sans-serif",
        color: "#475569",
        textAlign: "center",
        zIndex: 2,
      },
      {
        id: "required-form-box",
        type: "shape",
        shape: "rect",
        x: 110,
        y: 320,
        width: 860,
        height: 860,
        backgroundColor: "#ffffff",
        borderColor: "#e5e7eb",
        borderWidth: 2,
        zIndex: 3,
      },
      {
        id: "required-form-element",
        type: "form",
        x: 170,
        y: 380,
        width: 740,
        height: 700,
        zIndex: 30,
        requiredFormElement: true,
      } as any,
    ],
  };
}