export const ERROR_CODES = {
  AUTH_REQUIRED: "E001",
  SESSION_EXPIRED: "E002",
  INVALID_LOGIN: "E003",

  PERMISSION_DENIED: "E101",
  HOST_REQUIRED: "E102",
  SUPERHOST_REQUIRED: "E103",

  ORGANIZATION_REQUIRED: "E201",
  ORGANIZATION_NOT_FOUND: "E203",
  ORGANIZATION_INACTIVE: "E204",
  ORGANIZATION_ACCESS_DENIED: "E205",

  DATA_NOT_FOUND: "E301",
  INVALID_INPUT: "E303",
  DUPLICATE_RESOURCE: "E304",
  INVALID_REQUEST: "E305",

  // 추가 추천
  RATE_LIMIT_EXCEEDED: "E306",
  FEATURE_DISABLED: "E307",
  BACKUP_NOT_ALLOWED: "E308",
  RESTORE_NOT_ALLOWED: "E309",

  APPROVAL_FAILED: "E401",
  SETTLEMENT_FAILED: "E404",

  // 추가 추천
  REFUND_FAILED: "E405",

  FILE_UPLOAD_FAILED: "E501",
  STORAGE_LIMIT_EXCEEDED: "E503",

  // 추가 추천
  FILE_NOT_FOUND: "E504",
  INVALID_FILE_FORMAT: "E505",

  MESSAGE_SEND_FAILED: "E602",

  BACKUP_FAILED: "E701",
  RESTORE_FAILED: "E705",

  SMS_SEND_FAILED: "E802",
  EXTERNAL_API_FAILED: "E804",

  // 추가 추천
  EMAIL_SEND_FAILED: "E805",

  INTERNAL_SERVER_ERROR: "E902",
} as const;